[package]
name = "huevim"
version = "0.6.1"
edition = "2024"
license = "MIT"
description = "Neovim lua color scheme generator written in Rust."
homepage = "https://github.com/oahlen/huevim"
categories = ["command-line-utilities"]
keywords = ["neovim", "nvim", "colorscheme"]

[dependencies]
anyhow = "1"
lexopt = "0.3"
indexmap = "2.12"
regex = "1.12"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
toml = { version = "1", features = ["preserve_order"] }
